### ISSUE TITLE
Db Schema

### ISSUE THREAD

**Issue by javiermortiz** [HeroRoku/AuthMe#1]
Hi Jevon, the schema is looking good. I think you need another table "transactions" that is a join table between users and coinDetails that holds a count of how many shares you are buying/selling, a type (buy or sell), the userId and the coinDetailsId.

**Comment by HeroRoku** [comment]
thank you. 

transactions int pk autoincrement
coinDetail_id int
user_id
type varchar (buy/sell) 

is this what you are stating? I will get started on the database creation for the other tables and await confirmation to build this last table.

Thank you for all your assistance. I know you and Geoff are working tirelessly.

**Comment by gootieno** [comment]
Hi! 

It looks like the joins table above is what Javier was talking about. I did not see that change in the actual wiki but that is what you would be adding. Ideally what you are creating is a way to keep track of actual transactions. Assuming you implemented the joins table messaged above and it is just not updated in the wiki you should be good to go!

**Comment by HeroRoku** [comment]
yes I did. I will get the wiki updated shortly.
